# Generated by Django 6.1.1 on 2026-09-20 19:49

from django.db import migrations
import re


def create_profiles(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    Profile = apps.get_model('accounts', 'Profile')

    for user in User.objects.all():
        if Profile.objects.filter(user=user).exists():
            continue

        base_username = user.email.split('@')[0].lower()
        base_username = re.sub(r'[^a-z0-9_]', '_', base_username)
        base_username = base_username[:30]

        if len(base_username) < 3:
            base_username = f'user_{user.pk}'

        username = base_username
        counter = 1

        while Profile.objects.filter(username__iexact=username).exists():
            suffix = f'_{counter}'
            username = f'{base_username[:30 - len(suffix)]}{suffix}'
            counter += 1

        Profile.objects.create(
            user=user,
            username=username
        )


def delete_profiles(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    Profile = apps.get_model('accounts', 'Profile')

    Profile.objects.filter(user__in=User.objects.all()).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.RunPython(
            create_profiles,
            delete_profiles
        ),
    ]