# Generated by Django 6.1.1 on 2026-09-30 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='collection',
            name='unique_collection_slug_per_parent',
        ),
        migrations.RemoveConstraint(
            model_name='document',
            name='unique_document_slug_per_parent',
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('owner', 'slug'), name='unique_root_collection_slug'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('owner', 'parent', 'slug'), name='unique_child_collection_slug'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('owner', 'slug'), name='unique_root_document_slug'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('owner', 'parent', 'slug'), name='unique_child_document_slug'),
        ),
    ]
